language: node_js
node_js:
- 4
- 5
- stable

sudo: required

addons:
  firefox: "39.0"

services:
  - docker

os:
- linux
- osx

matrix:
  exclude:
  - os: osx
    node_js: 4
  - os: osx
    node_js: 5

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated xctool || brew upgrade xctool; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CHROME_BIN=chromium-browser; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install google-chrome; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
- docker pull dmkent/cattrack
- docker run -d -p 8000:8000 dmkent/cattrack

before_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then nohup bash -c "webdriver-manager start 2>&1 &"; fi

after_failure:
- cat /home/travis/build/mgechev/angular2-seed/npm-debug.log

branches:
  only:
    - master
    - /^release-.*$/

notifications:
  email: true

cache:
  directories: node_modules

script:
- npm run tests.all
- npm run build.prod
- npm run gulp build.prod.tar

deploy:
  provider: releases
  api_key:
    secure: "mUw5S+TQvesZsQncrO49JGQlzelr/uXqa1U5/B0uKVOCANbHqpw0ugGlXzSck0MNL7JLxMXnxU3sz68lpSpWgcCz9QFIw/jRf+b91mUFS3X9syUqMSBAuYlIvAU5Pw0GNxegBnDCHZbaQihbzWQF97k+WUVlO3NYoFirtMoKNjWBB7mWeLkPDEVvjjEfTd9Ur3v0xfK3/8qOz9yd4tpGXN9Y004U05+wpniVN4Vad8yM8SucbN3Z1XXcqquR6CkaCGnD521dUjjxw7Uu0tugOYBEew5sDSAMG6FR+ANnICf3+XV4T18HgQCqwhA7Gab/e5hxqRkq7/c3MEz7UnkYIcJlQlq8CFj+ADvegq5mrotsYpwJcTHh4RgRZrvsWMkAj1yQ5CR0albGUayozrgVp0S1CTyp3YDoi1/dFkP884tqq/eW7FGen34EM46mZDjjSSINprrK8fOGawgh83uNP9ze94br2nYevcVOHUCdAKHwdgL1sL2Mx8dD33yVf1ESHHm2oiIZNobUhXGxYtjOI1j1s3I4PnrsHmx/5vcqkVGevx1WdAj3SZrtAtGD0SIVWaXjXIl5NNGcc/r7vWPEMHABVVCq2OhgVzPHkZjhyC4l3AbQb9cjgbvVNtZhx6QlppGbzeSkza2v+gJaUg+2zmIaWjUHEQqG/UWpOUR4R5k="
  file: dist/cattrack-client.tar.gz
  on:
    repo: dmkent/cattrack-client
    tags: true
    node_js: 5
