language: node_js
node_js:
- 4
- 5
- stable

sudo: false

os:
- linux
- osx

matrix:
  exclude:
  - os: osx
    node_js: 4
  - os: osx
    node_js: 5

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated xctool || brew upgrade xctool; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CHROME_BIN=chromium-browser; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install google-chrome; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi

before_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then nohup bash -c "webdriver-manager start 2>&1 &"; fi

after_failure:
- cat /home/travis/build/mgechev/angular2-seed/npm-debug.log

branches:
  only:
    - master
    - /^release-.*$/

notifications:
  email: true

cache:
  directories: node_modules

script:
- npm run tests.all
- npm run build.prod
- npm run gulp build.prod.tar

deploy:
  provider: releases
  api_key:
    secure: EBFN1IzfzJgBuS6qi5H0HbshYfrBiyOPAP/efyBPumqEd0pCmAmKjb+oAweKch5dYPcAAFqDbcxQJFGpLcvJZgbMzDkN0Lo3+voqGYV76EFxCMX4ChpEr8/DJR8RiaD8TZ33Ch4OqVZseCl6OqERpnU5H0V3At7ZqS490JLP7AzS1oBomte1qsgMpBJ4zh9qg9t/FcwOQq0QWEA+ngWj2RJTXbCO2RZFqQLgc7BuoFCWzTMNskzI8PRJCSu/asVdbdJEjVV55SRiL5YJBU+HZYnXMTMeXTOCSQ6E7ahXax97WLOosGYk5+csPPi7QbR+LV78h8ihzAOB5R5xySpFDpvd4CDCX1+YW8G0L31kRMtlcSL0vMdV94aeSHbCEFK57UAU/QYehwhKr1SEpX3GMg7Cmu/EErS8wGo9UVdGLF0nY3CbdY3FRIYMrntgyCIYvRywT/s+vbi2MFRi+QB8vbFG8xHu7Iv8xwsDrUtre2WQHJlcgc3u5qZwVVFhDooIE58JFpcQSIdVE4DBsvKj+6cyjDTP/d+Xmcmq712ZQyZEBxWFBKIXooTIOGGDFD5WFA32xre8dX0w8KpWhVII02L+uesZCKAovoTxyD1oPdk+mvCPbj0egm3VBEwIMOtUM8Ef6PWKRxLOHqnOt4aDBA8V+dhppYDYQlaLaHX20eg=
  file: dist/cattrack-client.tar.gz
  on:
    repo: dmkent/cattrack-client
    tags: true
    node_js: 5
